version: "3.9"

services:
  redis-commander:
    container_name: ${APP_NAME}_${DOCKER_APP_NAME}_redis_commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - ${DOCKER_REDIS_COMMANDER_PORT}:8081
    networks:
      - rentnet

networks:
  rentnet:
    external: true
