version: "3.9"

services:
  redis:
    container_name: ${APP_NAME}_${DOCKER_APP_NAME}_redis
    hostname: redis
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data:/data
    ports:
      - ${DOCKER_REDIS_PORT}:6379
    networks:
      - rentnet

networks:
  rentnet:
    external: true
